### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by jerdog** [hypertrack/hypertrack-python#4]
When I clone and follow the instructions and then attempt to run `python example.py` I get the following:

```
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import hypertrack
  File "/Users/jerdog/work/hypertrack/hypertrack-python/hypertrack/__init__.py", line 5, in <module>
    from hypertrack.resource import (
  File "/Users/jerdog/work/hypertrack/hypertrack-python/hypertrack/resource.py", line 11, in <module>
    import requests
ImportError: No module named requests
```

**Comment by arjun27** [comment]
Cloning doesn't install the python package and its dependencies. Can you do a `pip install hypertrack` as given in the readme?

https://github.com/hypertrack/hypertrack-python#installation

**Comment by jerdog** [comment]
Cloned and followed the instructions which included 'pip install hypertrack'. I will dump and perform steps again

**Comment by jerdog** [comment]
@arjun27 I re-ran the process and when I do the `pip install hypertrack` command it gives me:
```
$ pip install hypertrack
Requirement already satisfied: hypertrack in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: requests>=2.6.0 in /usr/local/lib/python2.7/site-packages (from hypertrack)
```

When I run `python example.py` I get the same error that started this issue

**Comment by arjun27** [comment]
looks like a python configuration issue. my hypothesis is that the `python` commands and `pip` commands are pointing to different python setups on your machine. I would recommend the following

1. run python, and try importing requests. (this should return an error too.)
2. run pip install with pip as a python module, which would look like `python -m pip install hypertrack`
3. verify list of packages installed for your python setup by doing `python -m pip list`

**Comment by jerdog** [comment]
yeah I think there's a python config issue:

```
$ python -m pip install hypertrack
/usr/bin/python: No module named pip
$ python -m pip list
/usr/bin/python: No module named pip
```
